CREATE TABLE BOOK (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	isbn varchar(255) not null,
	name varchar(255) not null,
	genre varchar(255) not null
);

create sequence book_sequence start with 1 increment by 1;

insert into BOOK (isbn, name, genre) values ('978-4-10-206602-7', 'IT', 'Terror');